### ISSUE TITLE
Build error in 2.1.0

### ISSUE THREAD

**Issue by jibon57** [DroidNinja/Android-FilePicker#115]
Hello,

First of all thanks for the library. I am using this library to develop one of `NativeScript plugin` here: https://github.com/jibon57/nativescript-mediafilepicker

It was working as expected till `2.0.8`. Today I tried to update the plugin for `2.1.0`. But I got following error:

```
Skip droidninja.filepicker.adapters.FolderGridAdapter
        Error: java.lang.NullPointerException
Skip droidninja.filepicker.adapters.PhotoGridAdapter
        Error: java.lang.NullPointerException
```

When I am trying to open the picker it's giving hard crash.

```
System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;
System.err:     at droidninja.filepicker.fragments.MediaFolderPickerFragment.onCreate(MediaFolderPickerFragment.java:94)
System.err:     at android.support.v4.app.Fragment.performCreate(Fragment.java:2226)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
System.err:     at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1085)
System.err:     at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:973)
System.err:     at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:97)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2197)
System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
System.err:     at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2034)
System.err:     at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
System.err:     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1239)
System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1087)
System.err:     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1613)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
System.err:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
System.err:     at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1117)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:642)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:621)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.Glide" on path: DexPathLi
st[[zip file "/data/app/org.nativescript.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.demo-1/l
ib/x86, /data/app/org.nativescript.demo-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     ... 61 more
ActivityManager: Process org.nativescript.demo (pid 6251) has died
ActivityManager: cleanUpApplicationRecord -- 6251
```

But in `2.0.8` everything is OK. Any suggestion? Thanks in advance :)

Thanks
Jibon

**Comment by DroidNinja** [comment]
This is not library issue. There are tons of this issue already in glide and other picker libraries issues. It is a build issue (compile time only). There are different solutions to this . As I am not able to replicate this issue. Check out these links :
https://github.com/zhihu/Matisse/issues/74
https://stackoverflow.com/questions/44734189/java-lang-noclassdeffounderror-failed-resolution-of-lcom-bumptech-glide-glide

**Comment by kjanos0502** [comment]
Same issue here since 2.0.9, couldn't find a working solution..

**Comment by programmeraditya** [comment]
I had the same issue after upgrading to 2.1.0 from 2.0.8. 
Searched everywhere, but unable to find a solution.

**Comment by programmeraditya** [comment]
I switched back to 2.0.8 and everything works fine now. I think it's really a problem with the library.

**Comment by DroidNinja** [comment]
@programmeraditya sample project is building fine. I am not able to replicate this error. :(

**Comment by programmeraditya** [comment]
I will use the library with some other projects of mine and see what happens. Meanwhile, can you add the Folder View for documents as well? It would be extremely useful.
@DroidNinja

**Comment by jibon57** [comment]
@DroidNinja Thanks for hints. I tried but didn't get any success for new version. Old version 2.0.8 is working but haven't get success in new release. I can't test the demo app as I am using NativeScript not Android native directly.

**Comment by glidodroid** [comment]
Same issue in version 2.1.2.

**Comment by vinod1988** [comment]
@DroidNinja 
**There is an issue with the new version.  Please have look log for your help.**

I have just created one project and added the library and try to call a photo picker its crashed.




 java.lang.NoClassDefFoundError: com.bumptech.glide.Glide
                                                                           at droidninja.filepicker.fragments.MediaFolderPickerFragment.onCreate(MediaFolderPickerFragment.java:93)
                                                                           at android.support.v4.app.Fragment.performCreate(Fragment.java:2339)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                           at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                           at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                                                                           at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                           at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                           at android.view.View.measure(View.java:17495)
                                                                           at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                           at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                           at android.view.View.measure(View.java:17495)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                           at android.view.View.measure(View.java:17495)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                                                                           at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
                                                                           at android.view.View.measure(View.java:17495)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                           at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                           at android.view.View.measure(View.java:17495)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                                           at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
                                                                           at android.view.View.measure(View.java:17495)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                           at android.view.View.measure(View.java:17495)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                           at android.view.View.measure(View.java:17495)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                           at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
                                                                           at android.view.View.measure(View.java:17495)
                                                                           at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2285)
                                                                           at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1396)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1595)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6637)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:614)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:584)
                                                                       	at android.view.Choreographer$Fra

**Comment by DroidNinja** [comment]
@vinod1988 Is it crashing with the sample from latest version?

**Comment by MauriPastorini** [comment]
I had the same problem using a glide version before 4.5.0. 
So, I solved adding the dependency: 
`compile 'com.github.bumptech.glide:glide:4.5.0'`

**Comment by ameybawiskar** [comment]
I Facing Error After Adding 
**"  compile 'com.droidninja:filepicker:2.1.3' "**
 java.lang.NoSuchMethodError: No virtual method load(Ljava/io/File;)Lcom/bumptech/glide/RequestBuilder; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.example.amey.testprojectfilepicker--NJAFURWrFGrPf-gzmd7bQ==/base.apk)
                                                                                            at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:71)

**Comment by sheilambadi** [comment]
@ameybawiskar did you get a solution? I'm facing the same issue

**Comment by jibon57** [comment]
Finally got it solved as bellow:

```
dependencies {
	compile 'com.droidninja:filepicker:2.1.5'
	implementation 'com.android.support:appcompat-v7:27.1.1'
        implementation 'com.android.support:design:27.1.1'
        implementation  'com.android.support:recyclerview-v7:27.1.1'
	api 'com.github.bumptech.glide:glide:4.6.1'
}

```
